title = "HAO JIAYI"
baseURL = "https://haojiayi.top/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false
defaultContentLanguage  = "en"
defaultContentLanguageInSubdir = true


[languages]
  [languages.en]
    contentDir = 'content/english'
    languageName = 'English'
    weight = 10
  [languages.zh]
    contentDir = 'content/chinese'
    languageName = '中文'
    weight = 20
  [languages.ja]
    contentDir = 'content/japanese'
    languageName = '日本語'
    weight = 30

# [params]
# address = "Adachi, Tokyo"
# email = "iamhaokaki@gmail.com"
# favicon = "/favicon.ico"
# firstName = "Hao"
# lastName = "Jiayi"
# phone = "1-555-555-1234"
# profileImage = "img/haojiayi.jpg"
# showQr = false
# showContact = true
# showBoards  = true
# showCertifications = true
# showSocializations = true
# sections = ["skills","publications","creations","contributions","experience","education","blog"]

[languages.en.params]
address = "Adachi, Tokyo"
email = "iamhaokaki@gmail.com"
favicon = "/favicon.ico"
firstName = "Hao"
lastName = "Jiayi"
phone = "08060792112"
profileImage = "img/haojiayi.jpg"
showQr = false
showContact = true
showBoards  = false
showCertifications = false
showSocializations = true
# sections = ["skills","publications","creations","contributions","experience","education","blog"]
sections = ["education","skills","experience",]


[languages.zh.params]
address = "东京都足立区"
email = "iamhaokaki@gmail.com"
favicon = "/favicon.ico"
firstName = "郝"
lastName = "佳毅"
phone = "08060792112"
profileImage = "img/haojiayi.jpg"
showQr = false
showContact = true
showBoards  = false
showCertifications = false
showSocializations = true
sections = ["education","skills","experience"]


[languages.ja.params]
address = "東京都足立区"
email = "iamhaokaki@gmail.com"
favicon = "/favicon.ico"
firstName = "郝( ハオ )"
lastName = "佳毅( カキ)"
phone = "08060792112"
profileImage = "img/haojiayi.jpg"
showQr = false
showContact = true
showBoards  = false
showCertifications = false
showSocializations = true
sections = ["education","skills","experience"]




[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

# [[params.handles]]
#     name = "LinkedIn"
#     link = "https://www.linkedin.com/in/edwardwebb/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/yanjiemao/"

# [[params.handles]]
#     name = "Keybase"
#     link = "https://keybase.io/edwardawebb"
#     icon = "keybase"
    
# [[params.handles]]
#     name = "Bluesky"
#     link = "https://bsky.app/profile/webbinaro.dev"
#     icon = "bluesky"

# [[params.handles]]
#     link = "https://stackoverflow.com/users/82880/eddie"
#     name = "Stack Overflow"
#     icon = "stack-overflow"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
